# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'My S2 Game' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for My S2 Game
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'UIScrollView-InfiniteScroll'
  pod 'SDWebImage'

  target 'My S2 GameTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'My S2 GameUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
